### PR TITLE
Update Doorbell.m

### PR DESCRIPTION
**Pull request by cmaster11**
Fixed outdated SDK version number (triggers a warning in the dashboard, saying that you're not using the latest SDK).

### CODE REVIEW

**Comment by manavo** [comment]
That's great, thanks @cmaster11!

**Comment by manavo** [comment]
I'll have to re-tag with a new version, and to be sure to get the version updated correctly. Thanks again for finding this @cmaster11!

**Comment by cmaster11** [comment]
You're welcome!

**Comment by manavo** [comment]
Just tagged a new version, nothing new, just fixes that pesky version number bug. Thanks again!

**Pull request merged**
