### PR TITLE
Add Doorbell SDK as framework

### PR DESCRIPTION
**Pull request by shritekale**
This PR adds the support to add the Doorbell SDK as static framework.

### CODE REVIEW

**Comment by manavo** [comment]
Hey! Thanks for the PR, great to have you contributing!

I have a (potentially) silly question. I'm not sure I quite understand what this adds to it. Would it help include Doorbell into existing projects in a different way?

Just want to make sure I understand what it does before merging it in!

Thanks :smile:

**Comment by manavo** [comment]
Hey @dhardiman and @shritekale! Thanks for the PR!

I have a (potentially) silly question. I'm not sure I quite understand what this adds to it. Would it help include Doorbell into existing projects in a different way?

Just want to make sure I understand what it does before merging it in!

Thanks :smile:

**Comment by dhardiman** [comment]
Hi @manavo ,

We don't use cocoa pods here, so this just allows us to build the code as a dynamic framework to link to our app. Should give you carthage support for free as well, for people going that route. https://github.com/Carthage/Carthage/

Cheers

Dave

**Comment by manavo** [comment]
Awesome, thanks for the explanation Dave! :smile: 

Merged!

**Pull request merged**
